#!/bin/sh

echo "./bin/TOrder data/TAILARD_5_20_1.dat   1278  50   0.2 300.0  3600    2>>result1.txt >>LOG1" >>LOG1
      ./bin/TOrder data/TAILARD_5_20_1.dat   1278  50   0.2 300.0  3600    2>>result1.txt >>LOG1

echo "./bin/TOrder data/TAILARD_5_20_1.dat   1278  1000   0.3 2.0  3600    2>>result1.txt >>LOG1" >>LOG1
      ./bin/TOrder data/TAILARD_5_20_1.dat   1278  1000   0.3 2.0  3600    2>>result1.txt >>LOG1

echo "./bin/TOrder data/TAILARD_5_20_2.dat   1359  10000  0.2 3.0  3600    2>>result1.txt >>LOG1" >>LOG1
      ./bin/TOrder data/TAILARD_5_20_2.dat   1359  10000  0.2 3.0  3600    2>>result1.txt >>LOG1

echo "./bin/TOrder data/TAILARD_5_20_2.dat   1359  1000   0.8 1.5  3600    2>>result1.txt >>LOG1" >>LOG1
      ./bin/TOrder data/TAILARD_5_20_2.dat   1359  1000   0.8 1.5  3600    2>>result1.txt >>LOG1

echo "./bin/TOrder data/TAILARD_5_50_1.dat   2724  10000  0.2 3.0  7200    2>>result1.txt >>LOG1" >>LOG1
      ./bin/TOrder data/TAILARD_5_50_1.dat   2724  10000  0.2 3.0  7200    2>>result1.txt >>LOG1

echo "./bin/TOrder data/TAILARD_5_50_1.dat   2724  10000  1.0 1.0  7200    2>>result1.txt >>LOG1" >>LOG1
      ./bin/TOrder data/TAILARD_5_50_1.dat   2724  10000  1.0 1.0  7200    2>>result1.txt >>LOG1
